"""C

Revision ID: 2fc47d542aaf
Revises: 8fcee7d9d510
Create Date: 2024-06-20 09:16:53.472940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc47d542aaf'
down_revision: Union[str, None] = '8fcee7d9d510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latest', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('search', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('popular', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='media_news_pkey')
    )
    # ### end Alembic commands ###
