"""Change default table news

Revision ID: 554ffe2aae5e
Revises: 2d525d9e0b96
Create Date: 2024-06-18 16:16:26.928528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554ffe2aae5e'
down_revision: Union[str, None] = '2d525d9e0b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
