"""Schema crawler_sosmed

Revision ID: 8fcee7d9d510
Revises: 04d009744842
Create Date: 2024-06-19 15:40:48.080451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcee7d9d510'
down_revision: Union[str, None] = '04d009744842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_socmed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url_search', sa.Text(), nullable=False),
    sa.Column('url_comment', sa.Text(), nullable=False),
    sa.Column('url_hashtag', sa.Text(), nullable=False),
    sa.Column('url_video', sa.Text(), nullable=False),
    sa.Column('api_host', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sosmed')
    op.alter_column('crawler', 'code',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(),
               nullable=False)
    op.alter_column('crawler', 'api_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawler', 'api_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('crawler', 'code',
               existing_type=sa.String(),
               type_=sa.CHAR(length=4),
               nullable=True)
    op.create_table('sosmed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url_search', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url_comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.CHAR(length=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sosmed_pkey')
    )
    op.drop_table('crawler_socmed')
    # ### end Alembic commands ###
