"""Mengubah schema Media News

Revision ID: d2d524f265c3
Revises: 5a09c2965c68
Create Date: 2024-06-19 10:58:11.647251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d524f265c3'
down_revision: Union[str, None] = '5a09c2965c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_news', sa.Column('latest', sa.Text(), nullable=False))
    op.add_column('media_news', sa.Column('search', sa.Text(), nullable=False))
    op.add_column('media_news', sa.Column('popular', sa.Text(), nullable=False))
    op.drop_column('media_news', 'url_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_news', sa.Column('url_source', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('media_news', 'popular')
    op.drop_column('media_news', 'search')
    op.drop_column('media_news', 'latest')
    # ### end Alembic commands ###
